name: Weekly link checker

on:
  schedule:
    # Run at midnight every sunday
    - cron: "0 0 * * 0"

jobs:
  weekly-broken-link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          config-file: ".github/broken-links-configuration.json"

      - name: Create Issue
        if: failure()
        uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          filename: .github/action-issue-template.md
          assignees: tvcsantos
